name: Test Build

on:
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress site
        run: npm run docs:build

      - name: Check build output
        run: |
          if [ ! -d "docs/.vitepress/dist" ]; then
            echo "Build failed - dist directory not found"
            exit 1
          fi
